### PR TITLE
Jc/api options parameter

### PR DESCRIPTION
**Pull request by joao-conde**
| - | - |
| --- | --- |
| Issue | Fix https://github.com/ripe-tech/pconvert-rust/issues/21 |
| Dependencies | None |
| Decisions | 1. `blend_*` methods now receive an additional `options` argument which is a map of optional settings with corresponding values (*e.g.* python dict `options = {"num_threads": 5})` <br> 2. Current supported options are `num_threads` (if 0 or less, methods are single-threaded), `compression` and `filter` types (lower case strings of the enum versions of `image::png::CompressionType` and `image::png::FilterType`) <br> 3. Note that the WASM module can't make use of the `std::thread` API, and since it still does not make use of web workers, there is no need to pass `num_threads` and since the resultant file is not compressed or "filtered" before writing (because is is not written to a file system), this PR does not implement `options`for the WASM module. Future web workers implementations and corresponding PRs should pass these optional parameters (like `num_web_workers`|

### CODE REVIEW

**Comment by joamag** [comment]
@joao-conde please fix the conflicts

File: assets/demo/wasm/index.css [hunk 1]
```diff
@@ -1,3 +1,77 @@
+<<<<<<< HEAD
```
Comment (joamag) [inline assets/demo/wasm/index.css:1]: bad merge?

File: assets/demo/wasm/index.js [hunk 2]
```diff
@@ -1,3 +1,241 @@
...
+
+function isJSONParsable(str) {
+  try {
+    JSON.parse(str);
+  } catch (e) {
+    return false;
+  }
+  return true;
+}
+=======
```
Comment (joamag) [inline assets/demo/wasm/index.js:238]: bad merge?

File: assets/demo/wasm/index.css [hunk 3]
```diff
@@ -1,3 +1,77 @@
...
+
+.left-container.algorithms {
+    height: 55%;
+}
+
+select#algorithm, select#compression, select#filter {
+    width: 100%;
+    margin-bottom: 1em;
+}
+=======
```
Comment (joamag) [inline assets/demo/wasm/index.css:74]: bad merge?

File: assets/demo/wasm/index.html [hunk 4]
```diff
@@ -1,3 +1,77 @@
...
+          <pre id="metadata"></pre>
+        </div>
+      </div>
+    </div>
+  </div>
+  <script src="./index.js"></script>
+</body>
+
+</html>
+=======
```
Comment (joamag) [inline assets/demo/wasm/index.html:74]: bad merge?

**Review by joamag — CHANGES_REQUESTED** [review]

**Comment by joamag** [comment]
@joao-conde let's be careful about merging conflicts

**Review by joamag — APPROVED** [review]
